# Generated by Django 4.0.7 on 2023-05-02 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishing_company', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('author', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, null=True)),
                ('publish_date', models.CharField(max_length=10)),
                ('number_pages', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=13)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='categories.category')),
                ('followers', models.ManyToManyField(related_name='following_books', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='publishing_company.publisher')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
