# Generated by Django 4.0.7 on 2023-05-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishing_company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='Name',
            new_name='name',
        ),
    ]
