# Generated by Django 4.0.7 on 2023-05-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='copies.copy'),
        ),
    ]
